server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dbpostgresql:5432/testreloadly?createDatabaseIfNotExist=true
    username: "postgres"
    password: "1234"
  reloadly:
    app:
      jwtSecret: reloadlyaTestSecretKey
      jwtExpirationMs: 86400000

